var lists = 
[
["sandwichList","pm new promotion","스파이시 이탈리안 아보카도","Spicy Italian Avocado","540 kcal","풍미 가득 살라미와 페퍼로니에 아보카도가 더해져 더욱 완벽해진 맛의 밸런스(기간한정 ~07.31)"],
["sandwichList","pm promotion","터키 베이컨 아보카도","Turkey Bacon Avocado","420 kcal","담백한 터키와 바삭한 베이컨 환상조합에 부드러운 아보카도는 신의 한수"],
["sandwichList","fl new promotion","베지 아보카도","Veggie Avocado","290 kcal","7가지 신선한 야채에 신선한 아보카도가 들어가 더욱 풍성하고 건강해진 한끼(기간한정 ~07.31)"],
["sandwichList","pm new","풀드포크","Pulled Pork","420 kcal","7시간 저온 훈연한 미국 정통 스타일의 리얼 바비큐 풀드포크는 오직 써브웨이에서"],
["sandwichList","cl","에그마요","Egg Mayo","480 kcal","친환경 인증 받은 농장에서 생산된 달걀과 고소한 마요네즈가 만나 더 부드러운 스테디셀러"],
["sandwichList","cl","이탈리안 비엠티","Italian B.M.T","410 kcal","7시간 숙성된 페퍼로니, 살라미 그리고 햄이 만들어내는 최상의 조화! 전세계가 사랑하는 No.1 베스트셀러!Biggest Meatiest Tastiest, It's B.M.T.!"],
["sandwichList","cl","비엘티","B.L.T","380 kcal","오리지널 아메리칸 베이컨의 풍미와 바삭함 그대로~"],
["sandwichList","cl","미트볼","Meatball","480 kcal","이탈리안 스타일 비프 미트볼에 써브웨이만의 풍부한 토마토 향이 살아있는 마리나라소스를 듬뿍"],
["sandwichList","cl","햄","Ham","290 kcal","기본 중에 기본! 풍부한 햄이 만들어내는 입 안 가득 넘치는 맛의 향연"],
["sandwichList","cl","참치","Tuna","480 kcal","남녀노소 누구나 좋아하는 담백한 참치와 고소한 마요네즈의 완벽한 조화"],
["sandwichList","fl","로티세리 치킨","Rotisserie Chicken","350 kcal","촉촉한 바비큐 치킨의 풍미가득. 손으로 찢어 더욱 부드러운 치킨의 혁명"],
["sandwichList","fl","로스트 치킨","Roasted Chicken","320 kcal","오븐에 구워 담백한 저칼로리 닭가슴살의 건강한 풍미"],
["sandwichList","fl","로스트 비프","Roasted Beef","320 kcal","청정 호주 쇠고기를 오븐에 구워 더욱 담백하고 풍부한 맛이 살아있는 비프 샌드위치"],
["sandwichList","fl","써브웨이 클럽","Subway Club","310 kcal","명실공히 시그니처 써브! 터키, 비프, 포크 햄의 완벽한 앙상블"],
["sandwichList","fl","터키","Turkey","280 kcal","280kcal로 슬림하게 즐기는 오리지날 터키 샌드위치"],
["sandwichList","fl","베지","Veggie Delite","230 kcal","갓 구운 빵과 신선한 7가지 야채로 즐기는 깔끔한 한끼"],
["sandwichList","pm","스테이크 & 치즈","Steak & Cheese","380 kcal","육즙이 쫙~풍부한 비프 스테이크의 풍미가 입안 한가득"],
["sandwichList","pm","터키 베이컨 아보카도","Turkey Bacon Avocado","420 kcal","담백한 터키와 바삭한 베이컨 환상조합에 부드러운 아보카도는 신의 한수"],
["sandwichList","pm","치킨 베이컨 랜치","Chicken & Bacon Ranch","610 kcal","바삭한 베이컨과 담백한 치킨의 이중주"],
["sandwichList","pm","써브웨이 멜트","Subway Melt","410 kcal","자신있게 추천하는 터키, 햄, 베이컨의 완벽한 맛의 밸런스"],
["sandwichList","pm","터키 베이컨","Turkey Bacon","360 kcal","담백한 터키와 바삭한 베이컨의 기분 좋은 만남"],
["sandwichList","pm","스파이시 이탈리안","Spicy Italian","480 kcal","살라미, 페퍼로니가 입안 한가득! 쏘 핫한 이탈리아의 맛"],
["sandwichList","pm","치킨 데리야끼","Chicken Teriyaki","370 kcal","담백한 치킨 스트립에 달콤짭쪼름한 써브웨이 특제 데리야끼 소스와의 환상적인 만남"],
["sandwichList","bf","블랙 포레스트햄 & 에그, 치즈","Black Forest Ham & Egg, Cheese","400 kcal","푹신한 오믈렛과 햄의 가장 클래식한 조화※아침메뉴 제공시간 : 오전 11시까지"],
["sandwichList","bf","웨스턴, 에그 & 치즈","Western, Egg & Cheese","370 kcal","토마토, 피망, 양파 세가지 야채가 더해져 더욱 신선한 하루 시작 ※아침메뉴 제공시간 : 오전 11시까지"],
["sandwichList","bf","베이컨, 에그 & 치즈","Bacon, Egg & Cheese","450 kcal","오리지널 아메리칸 베이컨으로 더욱 풍성한 아침 식사 ※아침메뉴 제공시간 : 오전 11시까지"],
["sandwichList","bf","스테이크, 에그 & 치즈","Steak, Egg & Cheese","440 kcal","육즙 가득 비프 스테이크로 든든한 아침 식사 ※아침메뉴 제공시간 : 오전 11시까지"],
["sandwichList","bf","해쉬브라운","Hash Brown","147 kcal","잘게 썬 감자를 노릇하게 구워 바삭하고 쫀득하게 즐기는 모닝 파트너 ※아침메뉴 제공시간 : 오전 11시까지"],
["saladList","pm new","스파이시 이탈리안 아보카도","Spicy Italian Avocado","370 kcal","풍미 가득 살라미와 페퍼로니에 아보카도가 더해져 더욱 완벽해진 맛의 밸런스"],
["saladList","pm","터키 베이컨 아보카도","Turkey Bacon Avocado","240 kcal","담백한 터키와 바삭한 베이컨 환상조합에 부드러운 아보카도는 신의 한수"],
["saladList","fl new","베지 아보카도","Veggie Avocado","120 kcal","7가지 신선한 야채에 신선한 아보카도가 들어가 더욱 풍성하고 건강해진 한끼"],
["saladList","pm new","풀드포크","Pulled Pork","250 kcal","7시간 저온 훈연한 미국 정통바비큐 풀드포크가 가득. 풍미 가득 풀드포크 찹 샐러드"],
["saladList","cl","이탈리안 비엠티","Italian B.M.T","230 kcal","7시간 숙성된 페퍼로니, 살라미 그리고 햄이 만들어내는 최상의 조화! 전세계가 사랑하는 No.1 베스트셀러! Biggest Meatiest Tastiest, It's B.M.T. 찹 샐러드"],
["saladList","cl","비엘티","B.L.T","210 kcal","오리지널 아메리칸 베이컨의 풍미와 바삭함이 찹 샐러드에 그대로"],
["saladList","cl","미트볼","Meatball","310 kcal","이탈리안 스타일 비프 미트볼이 토핑된 찹 샐러드"],
["saladList","cl","햄","Ham","110 kcal","기본 중에 기본! 풍부한 햄 토핑 가득 찹 샐러드"],
["saladList","cl","참치","Tuna","310 kcal","남녀노소 누구나 좋아하는 담백한 참치와 고소한 마요네즈의 완벽한 조화"],
["saladList","cl","에그마요","Egg Mayo","300 kcal","친환경 인증 받은 농장에서 생산된 달걀과 고소한 마요네즈가 만나 더 부드러운 에그마요 찹 샐러드"],
["saladList","fl","로티세리 치킨","Rotisserie Chicken","170 kcal","촉촉한 바비큐 치킨의 풍미가득. 손으로 찢어 더욱 부드러운 치킨이 찹 샐러드에 쏙"],
["saladList","fl","로스트 치킨","Roasted Chicken","150 kcal","오븐에 구워 담백한 저칼로리 닭가슴살의 건강한 풍미"],
["saladList","fl","로스트 비프","Roasted beef","140 kcal","오븐에 구워 더욱 담백한 청정 쇠고기가 가득. 비프 찹 샐러드"],
["saladList","fl","써브웨이 클럽","Subway Club","140 kcal","터키, 비프, 포크 햄의 완벽한 앙상블과 즐기는 찹 샐러드"],
["saladList","fl","터키","Turkey","110 kcal","더 슬림하게 즐기자! 오리지날 터키 찹 샐러드"],
["saladList","fl","베지","Veggie Delite","60 kcal","7가지 야채만으로도 깔끔한 조화! 기본에 충실한 베지 찹 샐러드"],
["saladList","pm","스테이크 & 치즈","Steak & Cheese","210 kcal","육즙이 쫙~풍부한 비프 스테이크의 풍미 가득 스테이크치즈 찹 샐러드!"],
["saladList","pm","터키 베이컨 아보카도","Turkey Bacon Avocado","240 kcal","담백한 터키와 바삭한 베이컨 환상조합에 부드러운 아보카도는 신의 한수"],
["saladList","pm","치킨 베이컨 랜치","Chicken & Bacon Ranch","540 kcal","바삭한 베이컨과 담백한 치킨의 이중주"],
["saladList","pm","써브웨이 멜트","Subway Melt","188 kcal","자신있게 추천하는 터키, 햄, 베이컨의 발란스로 완성된 멜트 찹 샐러드"],
["saladList","pm","터키 베이컨","Turkey Bacon","280 kcal","담백한 터키와 바삭한 베이컨의 기분 좋은 만남"],
["saladList","pm","스파이시 이탈리안","Spicy Italian","310 kcal","살라미, 페퍼로니가 입안 한가득! 진짜 이탈리아의 맛 가득한 찹 샐러드"],
["saladList","pm","치킨 데리야끼","Chicken Teriyaki","230 kcal","담백한 치킨 스트립에 달콤짭쪼름한 써브웨이 특제 데리야끼 소스 토핑으로 더 풍성한 찹 샐러드"],
["toppingList","topping","더블업","Double Up","","주 재료를 2배로더 푸짐하게 즐기세요 15cm : 1,500원 / 30cm 3,000원"],
["toppingList","topping","에그마요","Egg Mayo","","신선한 달걀과고소한 마요네즈의 만남 15cm : 1,500원 / 30cm : 3,000원"],
["toppingList","topping","오믈렛","Omelet","","더 부드럽게, 더 고소하게 15cm : 1,100원 / 30cm : 2,200원"],
["toppingList","topping","아보카도","Avocado","","숲속의 버터 아보카도로 영양 UP 15cm : 1,100원 / 30cm : 2,200원"],
["toppingList","topping","베이컨","Bacon","","진한 풍미와 바삭한 베이컨으로특별한 나만의 써브웨이~ 15cm : 900원 / 30cm : 1,800원"],
["toppingList","topping","페퍼로니","Pepperoni","","입맛 당기는 페퍼로니로써브웨이를 더 맛있게! 15cm : 800원 / 30cm : 1,600원"],
["toppingList","topping","더블치즈","Double Cheese","","고소한 치즈를 2배로! 15cm : 800원 / 30cm : 1,600원"],
["sideDrink","sides","브로콜리 & 체더치즈 수프","Broccoli & Cheddar Cheese Soup","170 kcal","건강한 브로콜리와 짭쪼름한 체다치즈의 환상적인 조합"],
["sideDrink","sides","베이컨 포테이토 수프","Bacon Potato Soup","210 kcal","부드럽고 담백한 감자에 바삭한 베이컨의 찰떡궁합"],
["sideDrink","sides","더블 초코칩 쿠키","Double Chocolate Chip","210 kcal","부드러운 화이트초콜릿과 다크 초콜릿의 절묘한 조화로 더욱 풍부한 달콤함"],
["sideDrink","sides","초코칩 쿠키","Chocolate Chip","200 kcal","알알이 가득한 초코의가장 클래식한 달콤함"],
["sideDrink","sides","오트밀 레이즌","Oatmeal Raisin","200 kcal","캘리포니아 건포도와 귀리에 살짝더해진 계피향의 환상적인 조화"],
["sideDrink","sides","라즈베리 치즈케익","Raspberry Cheese Cake","200 kcal","부드럽고 풍부한 치즈와 새콤달콤 라즈베리의 달콤한 만남"],
["sideDrink","sides","화이트 초코 마카다미아","White Choco Macadamia","220 kcal","고소함 가득한 마카다미아와 달콤한 화이트 초콜릿의 환상 궁합"],
["sideDrink","sides","칩","Chip","","바삭바삭한 칩을 추가해 써브웨이를 즐겨보세요"],
["sideDrink","drink","탄산음료","Soda","",""],
["sideDrink","drink","커피","Coffee","",""],
["catering","sandwich","프레쉬 파티플래터","Fresh Party Platter","","터키, 햄, 참치, 에그마요, 클럽으로구성된 어디서든 신선하게 즐길 수 있는파티플래터"],
["catering","sandwich","베스트 파티플래터","Best Party Platter","","터키, 참치, 로스트비프, 이탈리안 비엠티,써브웨이 클럽으로 구성된 모두의 입맛을만족시키는 베스트 파티플래터"],
["catering","sandwich","자이언트 써브 90cm","Giant Sub 3feet","","보는재미, 먹는재미! 특별한 날은 자이언트써브로 더욱 특별하게※이탈리안 비엠티, 로스트비프, 햄,터키, 스파이시 이탈리안 중 선택"],
["catering","sandwich","자이언트 써브 180cm","Giant Sub 6feet","","보는재미, 먹는재미! 특별한 날은 자이언트써브로 더욱 특별하게※이탈리안 비엠티, 로스트비프, 햄,터키, 스파이시 이탈리안 중 선택"],
["catering","cookie","쿠키박스","Cookie box","","즐거운 순간을 5가지 맛의 쿠키와함께 즐기세요 (12개입)"],
["catering","cookie","쿠키플래터","Cookie Platter","","즐거운 순간을 5가지 맛의 쿠키와함께 즐기세요 (36개입)"],
["freshInfo","bread","허니오트","Honey Oat","230 kcal","고소한 위트빵에 오트밀 가루를 묻혀 고소함과 식감이 두배로"],
["freshInfo","bread","하티","Hearty Italian","210 kcal","부드러운 화이트빵에 옥수수가루를 묻혀 겉은 바삭하고 고소하며 속은 부드럽게"],
["freshInfo","bread","위트","Wheat","210 kcal","9가지 곡물로 만들어 건강하고 고소한 맛의 곡물빵"],
["freshInfo","bread","파마산 오레가노","Parmesan Oregano","210 kcal","부드러운 화이트빵에 파마산 오레가노 시즈닝을 묻혀 허브향 가득"],
["freshInfo","bread","화이트","White","210 kcal","가장 클래식한 빵으로 부드러운 식감이 매력 포인트"],
["freshInfo","bread","플랫브래드","Flat Bread","230 kcal","이름처럼 납작 모양에 피자도우처럼 쫀득한 맛이 일품"],
["freshInfo","vegetable","양상추","Lettuce","5 kcal",""],
["freshInfo","vegetable","토마토","Tomatoes","5 kcal",""],
["freshInfo","vegetable","오이","Cucumbers","5 kcal",""],
["freshInfo","vegetable","피망","Peppers","5 kcal",""],
["freshInfo","vegetable","양파","Red Onions","5 kcal",""],
["freshInfo","vegetable","피클","Pickles","5 kcal",""],
["freshInfo","vegetable","올리브","Olives","5 kcal",""],
["freshInfo","vegetable","할라피뇨","Jalapenos","5 kcal",""],
["freshInfo","vegetable","아보카도","Avocado","60 kcal",""],
["freshInfo","cheese","아메리칸 치즈","American Cheese","40 kcal",""],
["freshInfo","cheese","슈레드 치즈","Shredded Cheese","50 kcal",""],
["freshInfo","sauce","랜치드레싱","Ranch","110 kcal","고소한 마요네즈와 레몬즙의 만남! 고소함이 두배!"],
["freshInfo","sauce","마요네즈","Mayonnaise","110 kcal","말이 필요없는 고소함의 대명사, 마요네즈 소스"],
["freshInfo","sauce","스위트 어니언","Sweet Onion","40 kcal","써브웨이만의 특제 레시피로 만든 달콤한 양파소스"],
["freshInfo","sauce","허니 머스터드","Honey Mustard","30 kcal","겨자씨가 아낌없이 들어간 달콤한 머스터드 소스"],
["freshInfo","sauce","스위트 칠리","Sweet Chilli","30 kcal","멕시코 고추와 사과퓨레의 환상적인 조화! 기분좋은 달콤함"],
["freshInfo","sauce","핫 칠리","Hot Chilli","40 kcal","매운맛을 보고싶다면? 태국고추로 만든 써브웨이만의 매운맛"],
["freshInfo","sauce","사우스 웨스트","Chipotle","100 kcal","태국 고추 핫칠리와 고소한 마요네즈가 만난 이국적인 매콤한 맛"],
["freshInfo","sauce","머스타드","Yellow Mustard","5 kcal","겨자씨로 만든 오리지날 머스터드 소스"],
["freshInfo","sauce","디종홀스래디쉬","Horseradish","110 kcal","고소한 마요네즈와 고추냉이의 이색적인 만남! 매니아층을 사로잡은 매력No.1 소스"],
["freshInfo","sauce","사우전 아일랜드","Thousand Island","80 kcal","고소한 마요네즈와 토마토 케첩 그리고 신의한수 피클조각의 환상적인 만남"],
["freshInfo","sauce","이탈리안 드레싱","Italian Dressing","80 kcal","샐러드와 잘 어울리며 입맛을 돋워주는 새콤함"],
["freshInfo","sauce","올리브 오일","Olive Oil","45 kcal","담백하고 깔끔하게 즐기고 싶다면 주저하지 말고 올리브오일"],
["freshInfo","sauce","레드와인식초","Red Wine Vinaigrette","40 kcal","레드와인을 발효시켜 풍미가 가득한 식초"],
["freshInfo","sauce","소금","Salt","",""],
["freshInfo","sauce","후추","Black Pepper","",""],
["freshInfo","sauce","스모크 바비큐 소스","Smoke BBQ","","스모크 향과 달콤한 바비큐의 완벽한 조화(기간한정 02.01~04.31)"],
]